name: brotli
description: Dart package for providing brotli decompression.
author: Google, Inc.
homepage: https://github.com/google/brotli/dart
version: 0.1.0

dependencies:
  collection: ^1.14.6

dev_dependencies:
  mockito: ^3.0.0

environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"
